name: main

on:
  push:
    branches: [main]
  # 定时触发编译(每天早5点)
  #schedule:
     #- cron: '0 5 * * *'
  # 点☆Star触发开始编译
  #watch:  
     #types: [started]
  
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout main
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: 740162752/caddy-dns_plugins
              platform: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 # 你准备构建的镜像平台
              tag: bak # 默认latest，可以针对平台，修改tag
              dockerUser: 740162752 # docker hub userid
              dockerPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password
